#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

export PATH=$PATH:~/$OPENSHIFT_APP_NAME/virtenv/bin/
APP=myblog

source ~/$OPENSHIFT_APP_NAME/virtenv/bin/activate

if [ ! -f $OPENSHIFT_DATA_DIR/sqlite3.db ]
then
    echo "Copying ${OPENSHIFT_REPO_DIR}wsgi/myblog/sqlite3.db to $OPENSHIFT_DATA_DIR"
    cp ${OPENSHIFT_REPO_DIR}wsgi/myblog/sqlite3.db $OPENSHIFT_DATA_DIR/
else
    echo "Executing 'python ${OPENSHIFT_REPO_DIR}wsgi/myblog/manage.py syncdb --noinput'"
    python ${OPENSHIFT_REPO_DIR}wsgi/myblog/manage.py syncdb --noinput
fi
